title: blank
first_name: Birmjune
middle_name:
last_name: Kim
description: Personal academic homepage of Birmjune Kim. Projects, research, and news.
keywords: Birmjune Kim, artificial intelligence, efficient AI systems, model compression, quantization
lang: en
icon: ⚛️

url: https://Birmjune.github.io
baseurl:

navbar_fixed: true
footer_fixed: true
back_to_top: true
max_width: 930px

collections:
  news:
    output: false
  projects:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include:
  - _pages
  - .nojekyll
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - EDITING.md
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - node_modules/
  - package.json
  - package-lock.json
  - purgecss.config.js
  - README.md
  - readme_preview/
  - requirements.txt
  - vendor/
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-cache-bust
  - jekyll-minifier
  - jekyll-sitemap
plugins_dir: _disabled_plugins

defaults:
  - scope:
      path: assets
    values:
      sitemap: false

sass:
  style: compressed

jekyll-minifier:
  compress_javascript: false
  exclude:
    - robots.txt
